### ISSUE TITLE
Potential security threat

### ISSUE THREAD

**Issue by ty-everett** [bitcoincashjs/cashaddrjs#6]
On your repo front page you are linking to a script on some external cdn.rawgit page. This external server could be compromised and the script changed. Because this is used to handle funds, we shouldn't do this. Attackers could change the remote script to change any address output to one they control, stealing funds.

While this is fairly obvious, it isn't a good idea to have on the front page because some disgruntled dev might use it and get unlucky. A simple reference to "cashaddrjs-0.2.8.min.js" or something would make me feel a bit less uneasy.

Just my two satoshis, this is one of my first issues on GitHub so let me know if this is in the wrong place

**Comment by knoxcard** [comment]
You raise a good point .  I am honestly suggesting to never use the CDN ever.  Always download the script and reference your local copy to make this scenario impossible.

**Comment by ty-everett** [comment]
Should we update README.md on all the repos to reflect this.

**Comment by knoxcard** [comment]
I'd say so, I am not one of the project maintainers, You would have to edit the doc and generate pull request.

**Comment by ealmansi** [comment]
> I am honestly suggesting to never use the CDN ever. Always download the script and reference your local copy to render this scenario impossible.

This sounds like the best advice. Would be happy to merge an addition to the README file clarifying this. I don't think removing the link to `raw.git` is really necessary, since it's useful for trying out the library and it's ultimately the developer's responsibility to keep their apps safe. I'd call it "promoting bad security practices" rather than a potential security threat, which would be completely fixed by just adding a note in the README file.
